version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
#    depends_on:
#      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - /home/roma/Desktop/Inception/srcs/requirements/nginx/public/html:/var/www/
    restart: always
