version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
     - wordpress
     - mariadb
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/html
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
    restart: always
    networks:
      - inception


  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_ROOT: ${DB_ROOT}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
        WP_URL: ${WP_URL}
        WP_TITLE: ${WP_TITLE}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
        WP_USER_EMAIL: ${WP_USER_EMAIL}
        WP_USER: ${WP_USER}
        WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception
    env_file:
      - .env


volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/${USER}/data/wordpress

  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/${USER}/data/mariadb


networks:
  inception:
    driver: bridge
