version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
     - wordpress
     - mariadb
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/html
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
    restart: always
    networks:
      - inception


  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - .env



  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception
    env_file:
      - .env


volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/rshatra/data/wordpress

  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/rshatra/data/mariadb


networks:
  inception:
    driver: bridge
